language: python

python:
  - "2.7"
  - "3.5"

git:
  depth: 1

cache:
  - pip

env:
  - BUILD_LIB=1

install: 
  - "pip install -r requirements.txt"

services: 
  - postgresql

before_script:
  - psql -c 'create database mowrtest;' -U postgres

script:
  - nose2
