language: python

python:
  - "2.7"
  - "3.5"

git:
  depth: 1

cache:
  - pip

env:
  - BUILD_LIB=1 PATH=$PATH:$(pwd)/yara

install: 
  - "pip install -r requirements.txt"
  - "git clone https://github.com/plusvic/yara && cd ./yara && ./bootstrap.sh && ./configure && make && cd ../"

services: mongodb

script: nosetests
