language: python

python:
  - "2.7"
  - "3.5"

cache:
  - pip

env:
  - BUILD_LIB=1

install: 
  - "git clone https://github.com/nbs-system/php-malware-finder"
  - "pip install -r requirements.txt"

services: 
  - postgresql

before_script:
  - psql -c 'create database mowrtest;' -U postgres
  - psql -d mowrtest -c 'create extension fuzzystrmatch;' -U postgres

script:
  - nose2
